In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("newsgroups_train.csv")
df.head(5)

text  target       category
0  From: degroff@netcom.com (21012d)\nSubject: Re...       2      sci.space
1  From: ab@nova.cc.purdue.edu (Allen B)\nSubject...       1  comp.graphics
2  From: healta@saturn.wwc.edu (Tammy R Healy)\nS...       0    alt.atheism
3  From: capelli@vnet.IBM.COM (Ron Capelli)\nSubj...       1  comp.graphics
4  From: henry@zoo.toronto.edu (Henry Spencer)\nS...       2      sci.space

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
vectorize = CountVectorizer(max_features=1500)
vectors = vectorize.fit_transform(df['text'])
vectors = vectors.toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [4]:
for vec in vectors[0]:
    print(vec, end=" ")

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [5]:
vectors.shape

(1657, 1500)

In [6]:
X = vectors
y = df.target

In [7]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)



In [8]:
model = MultinomialNB()

model.fit(X_train, y_train)

predictions = model.predict(X_test)

predictions

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 0, 0, 0, 0, 1, 0, 1, 1, 0, 2, 1, 1,
       1, 2, 2, 1, 2, 1, 1, 0, 1, 2, 1, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 2,
       1, 0, 1, 1, 1, 1, 2, 1, 2, 0, 2, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 1, 2, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0,
       1, 2, 2, 1, 1, 2, 2, 2, 2, 0, 1, 0, 0, 0, 0, 2, 2, 2, 2, 1, 2, 0,
       1, 2, 2, 1, 0, 2, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 2, 1, 1, 0, 2, 2, 1, 1, 2, 0, 0, 2, 2, 0, 0, 1, 1, 0,
       2, 1, 0, 1, 0, 2, 0, 2, 2, 1, 1, 2, 0, 2, 1, 1, 1, 0, 2, 1, 1, 0,
       1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 0, 0, 2, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 2, 1, 0, 2, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0, 1, 2, 0, 0, 2, 1,
       0, 2, 0, 2, 2, 0, 1, 1, 1, 1, 2, 2, 2, 0, 1, 2, 1, 1, 0, 2, 1, 2,
       2, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 2, 2, 2, 0, 1,
       1, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 1, 0, 0, 2, 1, 1, 0, 2, 1, 2, 2,
       1, 0, 2, 2, 0, 1, 1, 1, 1, 0, 1, 2, 2, 0, 2,

In [9]:
# Assuming y_test and predictions are iterables of the same length
for y, pred in zip(y_test, predictions):
    print(f"y_test: {y}, predictions: {pred}")

y_test: 1, predictions: 1
y_test: 1, predictions: 1
y_test: 1, predictions: 1
y_test: 2, predictions: 1
y_test: 1, predictions: 1
y_test: 1, predictions: 1
y_test: 1, predictions: 1
y_test: 0, predictions: 0
y_test: 1, predictions: 1
y_test: 2, predictions: 2
y_test: 0, predictions: 0
y_test: 0, predictions: 0
y_test: 0, predictions: 0
y_test: 0, predictions: 0
y_test: 1, predictions: 1
y_test: 0, predictions: 0
y_test: 1, predictions: 1
y_test: 1, predictions: 1
y_test: 0, predictions: 0
y_test: 2, predictions: 2
y_test: 1, predictions: 1
y_test: 1, predictions: 1
y_test: 1, predictions: 1
y_test: 2, predictions: 2
y_test: 2, predictions: 2
y_test: 1, predictions: 1
y_test: 2, predictions: 2
y_test: 1, predictions: 1
y_test: 1, predictions: 1
y_test: 0, predictions: 0
y_test: 1, predictions: 1
y_test: 2, predictions: 2
y_test: 1, predictions: 1
y_test: 0, predictions: 0
y_test: 2, predictions: 2
y_test: 0, predictions: 0
y_test: 0, predictions: 0
y_test: 1, predictions: 1
y_test: 1, p

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
cm = confusion_matrix(y_test,predictions)
cm

array([[ 99,   1,   2],
       [  3, 108,   2],
       [  3,   4, 110]], dtype=int64)

In [11]:
cr = classification_report(y_test,predictions)
print(f"cr: {cr}")
accuracy = accuracy_score(y_test,predictions)
print(f"accuracy: {accuracy}")

cr:               precision    recall  f1-score   support

           0       0.94      0.97      0.96       102
           1       0.96      0.96      0.96       113
           2       0.96      0.94      0.95       117

    accuracy                           0.95       332
   macro avg       0.95      0.96      0.95       332
weighted avg       0.96      0.95      0.95       332

accuracy: 0.9548192771084337
